ARG CROSS_BASE_IMAGE
FROM $CROSS_BASE_IMAGE
RUN apt update -y
RUN apt install curl -y
RUN curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux \
  --extra-conf "sandbox = false" \
  --extra-conf "filter-syscalls = false" \
  --init none \
  --no-confirm
ENV PATH="${PATH}:/nix/var/nix/profiles/default/bin"
COPY . /app
WORKDIR /app
RUN nix \
    --option filter-syscalls false \
    develop
